EnvironmentAlias:
  allOf:
    - type: object
      properties:
        sys:
          $ref: "./sys.yml#/EnvironmentAliasSys"
      required:
        - sys
    - $ref: "./data.yml#/EnvironmentAliasData"
